# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application's code into the container at /app
COPY . .

# Make port 8501 available to the world outside this container
EXPOSE 8501

# Run app.py when the container launches using Gunicorn
# Gunicorn is a production-ready WSGI server.
# --bind 0.0.0.0:8501 makes the app accessible from outside the container.
# --workers 4 specifies the number of worker processes.
# main:app tells Gunicorn to run the 'app' object from the 'main.py' file.
# CMD ["gunicorn", "--bind", "0.0.0.0:8501", "--workers", "4", "main:app"]


CMD ["python" , "-u" , "main.py"]
