services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file :
      - ./.env 
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./key.json  
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./uploads:/app/uploads  

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: