
FROM python:3.11-slim


RUN apt-get update && apt-get install -y \
    libmagic1 \
    curl \
    && rm -rf /var/lib/apt/lists/*


COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv


WORKDIR /app


COPY uv.lock pyproject.toml ./


RUN uv sync --frozen --no-dev

COPY . .


ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1


EXPOSE 3000

# Run your FastAPI server
CMD ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]